### PR TITLE
Create .editorconfig

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
This should hopefully make the viewing more sensible.

### CODE REVIEW

**Comment by Lectem** [comment]
Thanks, let's give it a try

**Comment by Lectem** [comment]
Looks like it doesn't work (unless it needs some times to take effect).

https://github.com/ThePhrozenKeep/D2MOO/blob/782b469f9ef7422498a38e1925287ebe6e7835b4/source/D2Common/include/D2Collision.h#L38

Viewed from my account (properly configured):
image
Viewed from an incognito tab:
image

**Comment by Lectem** [comment]
Ok, fixed with https://github.com/ThePhrozenKeep/D2MOO/commit/113fa634c658419a87fb248feb8ac77dc1339777

**Comment by AudriusButkevicius** [comment]
Sweet, that was my next suggestion.

**Pull request merged**
