### PR TITLE
Add Unicode struct type

### PR DESCRIPTION
**Pull request by IAmTrial**
This adds a basic reimplementation of the Unicode struct with its constructors and `unsigned short` conversion operator. Other functions are significantly large and will be added in later pull requests.

I can confirm that the functions, with the exception with the default constructor closure, are generated with the exact same code in Visual C++ 6.0. In VS 2019, The default constructor closure does not generate unless the `Unicode::Unicode(unsigned short)` constructor is declared with `__declspec(dllexport)`. In addition, the default constructor closure generates the exact same code if the same constructor is also declared `inline`.

Otherwise, the code behaves exactly the same as vanilla Diablo II.

### CODE REVIEW

**Comment by Necrolis** [comment]
> The default constructor closure does not generate unless the Unicode::Unicode(unsigned short) constructor is declared with __declspec(dllexport). In addition, the default constructor closure generates the exact same code if the same constructor is also declared inline.

The default constructor should be an `inline`, this is evidenced by its terrible usage through-out D2Client.dll

**Comment by IAmTrial** [comment]
> > The default constructor closure does not generate unless the Unicode::Unicode(unsigned short) constructor is declared with __declspec(dllexport). In addition, the default constructor closure generates the exact same code if the same constructor is also declared inline.
> 
> The default constructor should be an `inline`, this is evidenced by its terrible usage through-out D2Client.dll

I agree that the constructor and other functions declared `inline` (e.g. unsigned short operator, constructors) should be declared `inline` in order to replicate the exact same code from vanilla. However, inline appears to also suppress the exporting of such functions without `__declspec(dllexport)`.

I am not entirely familiar with all the features of Visual C++ 6.0, so perhaps there are other ways to make this work. From what I currently am familiar with, we could choose one of the following:
- Declare the struct or functions with the attribute `__declspec(dllexport)`. The functions will also be declared `inline`. The current `D2LANG_DLL_DECL` macro will require changes to be made.
- Comment out the entries in the `.def` file. This will be problematic for DLL import.
- Do not declare the functions with `inline`. This will mean less similar code, but may not be an issue if accuracy is the priority, and not code generation.

**Comment by Lectem** [comment]
So after thinking about it a bit, I think it might be best for D2Lang to define `D2LANG_DLL_DECL` as `D2LANG_DLL_DECL __declspec( dllexport )` . You can then uncomment ``??_FUnicode@@QAEXXZ @10017 ; Unicode::`default constructor closure` `` as it is automatically generated with the current code.

We can also still use the module definition file (.def`) to remap functions to ordinals and use `NONAME` for those we need to keep anonymous.

Is there a reason for having the .cpp and .h files with different names ?

**Comment by IAmTrial** [comment]
Thanks for the update. I will adjust the changes accordingly.

To address the difference in naming of the `.h` and `.cpp` files, the `Unicode` struct consists of many different functions. Some functions deal with one single `Unicode` character and are non-static member functions. There are functions that deal with `Unicode` null-terminated strings. Other functions are involved with conversion between `Unicode` strings and some other type of string.

My plan is to introduce new files in separate pull requests. This is to keep the size of changes small. In order to more easily distinguish the purpose of these different functions, I have therefore defined them in this non-exhaustive list of files:
- `D2Unicode.h`: All functions need to be declared as members of the `Unicode` struct in this single file.
- `D2UnicodeChar.cpp`: Functions that deal with a single `Unicode` character (e.g. `Unicode::isASCII`). Most of these, if not all, are non-static member functions.
- `D2UnicodeStr.cpp`: Functions that accept at least one `Unicode*`, which is treated as a null-terminated `Unicode` string (e.g. `Unicode::strlen`). All of these are static member functions.
- `D2UnicodeUtf8.cpp`: Functions that deal with the conversion between null-terminated `Unicode` strings and UTF-8 strings (e.g. `Unicode::toUtf`, `Unicode::toUnicode`).
- `D2UnicodeSys.cpp`: Functions that deal with the conversion between null-terminated `Unicode` strings to sys strings (e.g. `Unicode::sys2Unicode`, `Unicode::loadSysMap`). I haven't yet reversed these functions, so the file name may be subject to change.

Also, vanilla Diablo 1.10 does not define all of the `Unicode` functions in one single `.cpp` file.
- `Unicode::sprintf` is defined in `\\D2Lang\\Unicode\\STRSUP.CPP`
- `Unicode::loadSysMap` is defined in `\\D2Lang\\Unicode\\UNISYS.CPP`

**Pull request merged**
